### PR TITLE
added a flag to print the version, then exit immediately

### PR DESCRIPTION
**Pull request by boner-cmd**
DC-9K here.

This is not ready to be pulled because I'm not smart enough to be able to set up a build environment to test things. But I'd love to chat with you about it whenever you're free so I _can_ test things before submitting PRs.

Frank_70#4663 in Discord mentioned wanting to be able to see the current version of btdex from the command line. I have not spent a lot of time reading your code and have not tested this. But I wanted to put in the PR so you could see it in case I forgot, and also to remind myself to ask you about building and dependencies.

### CODE REVIEW

**Comment by boner-cmd** [comment]
I was able to build the project and run a single test, and it worked. The change should be simple enough not to affect any other functionality.

**Review by ohager — APPROVED** [review]
Straightforward. I do not see any problem... :+1: (other than not fetching correct version :grin: )

**Comment by boner-cmd** [comment]
Not sure if version.properties is manually updated- if so, I updated it to the current version. If it's dynamic from somewhere else, a different fix is required.

**Comment by jjos2372** [comment]
The version on the properties file is just for local runs in debug mode. Releases get that from latest github tag.

All fine, I will merge.

**Comment by boner-cmd** [comment]
Oh, of course, I looked at your GitHub Actions yesterday but already forgot. Thank you!

**Pull request merged**
