### PR TITLE
added Belarusian language translation

### PR DESCRIPTION
**Pull request by ValentinChirikov**
Hi, please consider merging Belarusian translation. Thanks :)

### CODE REVIEW

**Comment by jjos2372** [comment]
Dear Valentin, thank you very much for the PR. We use https://www.transifex.com/btdex/btdex/dashboard/ for managing the translations and we get the files from there. That way we can have reviews and more easily translate new content as needed.

Can you please try to create a user there?

**Comment by ValentinChirikov** [comment]
> Dear Valentin, thank you very much for the PR. We use https://www.transifex.com/btdex/btdex/dashboard/ for managing the translations and we get the files from there. That way we can have reviews and more easily translate new content as needed.
> 
> Can you please try to create a user there?

it is already there :) I have done it finally today https://www.transifex.com/btdex/btdex/language/be_BY/

**Comment by jjos2372** [comment]
Oh, sorry. We should have it on soon then. Thank you very much again.

**Comment by shefass** [comment]
Thank you!

2021-05-23, sk, 20:55 jjos2372 ***@***.***> rašė:

**Comment by shefass** [comment]
Cool! We dropped Kotlin rewrite for brs. Do you want to contribute to
BRS (our node)? In general say what is interesting for you..maybe you
are interested in refactoring BRS? In my opinion it demands it.

2021-05-25, an, 10:52 ValentinChirikov ***@***.***> rašė:

**Comment by ValentinChirikov** [comment]
> Cool! We dropped Kotlin rewrite for brs. Do you want to contribute to BRS (our node)? In general say what is interesting for you..maybe you are interested in refactoring BRS? In my opinion it demands it. 2021-05-25, an, 10:52 ValentinChirikov ***@***.***> rašė:
> […](#)
> If there are some tasks Java/Kotlin I can help in my spare time. Have a nice day! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Why not ? I'll look for BRS. Are willing to move towards Kotlin, or clean-up / refactor BRS Java?

**Comment by shefass** [comment]
Our main dev JJos is old school..and we now dont have Kotlin dev. Please
keep all Java 8 compatible. Just now take some some simple file with bunch
of classes and other stuff and refactor it. Do not make a lot of work..You
need to earn respect "points" to our devs :) So small simple PRs with
motivation. We can discus in discord, just contact me or JJos

2021-05-25, an, 11:58 ValentinChirikov ***@***.***> rašė:

**Comment by shefass** [comment]
probably contact us in discord before doing work..we need to have
discussion about our style.

2021-05-25, an, 12:04 shefass ***@***.***> rašė:

**Comment by ValentinChirikov** [comment]
sure

**Comment by jjos2372** [comment]
> If there are some tasks Java/Kotlin I can help in my spare time. Have a nice day!

Hello. Sure, one thing that we started and you might try to help is the direct communication among users using encrypted messages. We can discuss that on the BTDEX/TRT discord server.

**Pull request closed without merging**
